version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: photo_challenge_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: photo_challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data:
